using Microsoft.CodeAnalysis;
using System;
using System.IO;
using System.Linq;

namespace NetOpCodeGenerator
{
    [Generator]
    public class HelloSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            //Debugger.Launch();

            var lines = File.ReadAllLines(context.AdditionalFiles.First().Path);

            var enumLines = lines.
                SkipWhile(l => !l.Contains("enum class OpCode")).
                Skip(2).
                TakeWhile(l => !l.Contains("}"));

            var enumValues = enumLines.Aggregate((a, b) => $"{a}{Environment.NewLine}{b}");

            string source = $@"// <auto-generated/>
using System;

namespace FlowCompiler
{{
    public enum OpCodes
    {{
        {enumValues}
    }}
}}
";
            context.AddSource($"RuntimeOpCodes.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization required for this one
        }
    }
}
